title: Cereza-Sol
description: Howdy! I am a junior programming developer currently studying at HCC. This is a hub for all of my updates on current and future projects. Take a look around!
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker